services:

  backend:
    build:
      # select directory to build
      context: ./backend
    container_name: emotion-backend
    ports:
      # select ports to build
      - "8000:8000"
    volumes:
      # presistent data
      - ./backend:/app
    environment:
      # type of environment
      - ENV=development
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: emotion-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - app-network
    depends_on:
      - backend

# allows for both front and backend to communicate
# defined outside of services
networks:
  app-network:
    driver: bridge
